import type { Metadata } from "next";
import "@/css/globals.css";
import "@/css/animation.css";
// import "../font/JosefinSans/JosefinSans.css";
import "@/fonts/client/JosefinSans/JosefinSans.css";
import "remixicon/fonts/remixicon.css";
import Sidebar from "@/components/client/ui/Sidebar";
import Footer from "@/components/client/ui/Footer";
import { AuthProvider } from "@/context/AuthContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <Sidebar />
          {children}
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
