export const CLEAR_ALERT = "CLEAR_ALERT";

export const SIGNUP_BEGIN = "SIGNUP_BEGIN";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILED = "SIGNUP_FAILED";

export const VERIFICATION_BEGIN = "VERIFICATION_BEGIN";
export const VERIFICATION_SUCCESS = "VERIFICATION_SUCCESS";
export const VERIFICATION_FAILED = "VERIFICATION_FAILED";

export const RESEND_BEGIN = "RESEND_BEGIN";
export const RESEND_SUCCESS = "RESEND_SUCCESS";
export const RESEND_FAILED = "RESEND_FAILED";

export const RESEND_TIMER = "RESEND_TIMER";

export const SIGNIN_BEGIN = "SIGNIN_BEGIN";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_FAILED = "SIGNIN_FAILED";

export const RESET_PASSWORD_EMAIL_BEGIN = "RESET_PASSWORD_EMAIL_BEGIN";
export const RESET_PASSWORD_EMAIL_SUCCESS = "RESET_PASSWORD_EMAIL_SUCCESS";
export const RESET_PASSWORD_EMAIL_FAILED = "RESET_PASSWORD_EMAIL_FAILED";

export const RESET_PASSWORD_BEGIN = "RESET_PASSWORD_BEGIN";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAILED = "RESET_PASSWORD_FAILED";
